"use client";

import { useEffect, useState, type FormEvent, type ReactNode } from "react";

type Path = "recommend" | "waitlist" | null;
type Status = "idle" | "loading" | "success" | "error";
const categories = ["Branding & design", "Packaging", "R&D / formulation", "Co-manufacturing", "Brokers & sales", "Amazon / ecommerce", "Growth marketing", "PR & communications", "Finance / fractional CFO", "Operations & supply chain", "Legal & regulatory", "Data & analytics", "Recruiting & talent", "Other"];
const input = "mt-1.5 w-full rounded-lg border border-border bg-white px-4 py-3 outline-none focus:border-accent focus:ring-2 focus:ring-accent/20";
const label = "block text-sm font-semibold";

export function CpgMatchIntake() {
  const [path, setPath] = useState<Path>(null);
  return <section className="relative z-10 -mt-9 bg-transparent pb-14 md:-mt-12 md:pb-20"><div className="mx-auto max-w-5xl px-4 text-center sm:px-6">
    <div className="rounded-2xl border border-border bg-background p-5 shadow-xl sm:p-8">
    <p className="text-sm font-semibold uppercase tracking-[.16em] text-muted">Choose how you want to participate</p>
    <div className="mx-auto mt-5 grid gap-4 sm:grid-cols-2">
      <button onClick={() => setPath("recommend")} className="group rounded-2xl bg-accent p-7 text-left text-white shadow-lg transition hover:-translate-y-0.5 hover:bg-accent-dark hover:shadow-xl sm:p-9"><span className="text-xs font-bold uppercase tracking-[.18em] text-white/75">Share your experience</span><strong className="mt-3 block text-2xl sm:text-3xl">Review a Vendor</strong><span className="mt-3 block font-semibold text-white/85">Submit one or more reviews and get early access <span className="inline-block transition group-hover:translate-x-1">→</span></span></button>
      <button onClick={() => setPath("waitlist")} className="group rounded-2xl border-2 border-ridge/25 bg-white p-7 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-ridge hover:shadow-lg sm:p-9"><span className="text-xs font-bold uppercase tracking-[.18em] text-muted">Be first to know</span><strong className="mt-3 block text-2xl sm:text-3xl">Join the Database Waitlist</strong><span className="mt-3 block font-semibold text-ridge">Takes less than a minute <span className="inline-block transition group-hover:translate-x-1">→</span></span></button>
    </div><p className="mt-5 text-sm text-muted">Review as many vendors as you&rsquo;d like. Submit at least one to receive early access.</p>
    </div>
  </div>{path && <Modal title={path === "recommend" ? "Review a Vendor" : "Join the Database Waitlist"} close={() => setPath(null)}>{path === "recommend" ? <Recommendation onDone={() => setPath(null)} /> : <Waitlist />}</Modal>}</section>;
}

function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) {
  useEffect(() => { const old = document.body.style.overflow; document.body.style.overflow = "hidden"; const key = (e: KeyboardEvent) => e.key === "Escape" && close(); window.addEventListener("keydown", key); return () => { document.body.style.overflow = old; window.removeEventListener("keydown", key); }; }, [close]);
  return <div className="fixed inset-0 z-[100] flex items-end justify-center bg-foreground/65 backdrop-blur-sm sm:items-center sm:p-6" role="dialog" aria-modal="true" aria-label={title} onMouseDown={e => e.target === e.currentTarget && close()}><div className="max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-t-2xl bg-white shadow-2xl sm:max-h-[90vh] sm:rounded-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-border bg-white px-5 py-4 sm:px-7"><strong>{title}</strong><button onClick={close} aria-label="Close" className="flex h-9 w-9 items-center justify-center rounded-full text-2xl text-muted hover:bg-background">×</button></div><div className="p-5 sm:p-8">{children}</div></div></div>;
}

function Waitlist() {
  const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState("");
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setStatus("loading"); const data = new FormData(e.currentTarget); try { const res = await fetch("/api/cpg-match", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "waitlist", ...Object.fromEntries(data), needs: data.getAll("needs") }) }); if (!res.ok) throw new Error(); setStatus("success"); } catch { setStatus("error"); setError("We couldn’t save your information. Please try again."); } }
  if (status === "success") return <Success title="You’re on the list." copy="We’ll let you know when CPG Match opens." />;
  return <form onSubmit={submit}><h3 className="text-2xl font-bold">Get launch access.</h3><p className="mt-2 text-muted">Where should we reach you, and what kind of help do you need?</p><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field name="firstName" text="First name" required /><Field name="lastName" text="Last name" required /><Field name="email" text="Work email" type="email" required /><Field name="brand" text="Company / brand" required /></div><fieldset className="mt-6"><legend className={label}>What kind of vendor(s) are you looking for?</legend><div className="mt-3 grid max-h-48 gap-2 overflow-y-auto rounded-lg border border-border p-3 sm:grid-cols-2">{categories.map(x => <label key={x} className="flex items-center gap-2 text-sm"><input type="checkbox" name="needs" value={x} className="h-4 w-4 accent-[var(--accent)]" />{x}</label>)}</div></fieldset><Submit status={status} text="Join the Database Waitlist" error={error} /></form>;
}

type ReviewerProfile = { firstName: string; lastName: string; email: string; brand: string; attribution: string };

function Recommendation({ onDone }: { onDone: () => void }) {
  const [step, setStep] = useState(1); const [status, setStatus] = useState<Status>("idle"); const [error, setError] = useState("");
  const [profile, setProfile] = useState<ReviewerProfile | null>(null);
  const titles = ["Who did you hire?", "How did it go?", "Help founders understand the fit.", "What should another founder know?"];
  function next(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const fields = Array.from(e.currentTarget.querySelectorAll<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>(`[data-step="${step}"] input,[data-step="${step}"] select,[data-step="${step}"] textarea`)); if (fields.every(x => x.reportValidity())) setStep(x => x + 1); }
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); setStatus("loading"); const values = Object.fromEntries(new FormData(e.currentTarget)); try { const res = await fetch("/api/cpg-match", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: "recommendation", ...values }) }); if (!res.ok) throw new Error(); setProfile({ firstName: String(values.firstName), lastName: String(values.lastName), email: String(values.email), brand: String(values.brand), attribution: String(values.attribution) }); setStatus("success"); } catch { setStatus("error"); setError("We couldn’t save your recommendation. Please try again."); } }
  if (status === "success") return <div className="py-8 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-accent-light text-2xl text-accent">✓</span><h3 className="mt-5 text-2xl font-bold">Thanks for your review!</h3><p className="mx-auto mt-3 max-w-md text-muted">Every recommendation makes CPG Match more useful. Have another vendor you&rsquo;ve worked with?</p><div className="mx-auto mt-7 flex max-w-sm flex-col gap-3"><button type="button" onClick={() => { setStep(1); setStatus("idle"); setError(""); }} className="rounded-lg bg-accent px-5 py-3 font-bold text-white hover:bg-accent-dark">Review Another Vendor</button><button type="button" onClick={onDone} className="rounded-lg border border-border px-5 py-3 font-bold hover:bg-background">I&rsquo;m Done</button></div></div>;
  return <form noValidate onSubmit={step === 4 ? submit : next}><div className="flex justify-between text-xs font-bold uppercase tracking-[.16em] text-muted"><span>Step {step} of 4</span><span>{["The vendor(s)", "Experience", "Context", "Final thoughts"][step - 1]}</span></div><div className="mt-3 h-1.5 rounded-full bg-background"><div className="h-full rounded-full bg-accent transition-all" style={{ width: `${step * 25}%` }} /></div><h3 className="mt-6 text-2xl font-bold">{titles[step - 1]}</h3>{step === 1 && <p className="mt-3 rounded-lg border border-accent/20 bg-accent-light/45 p-4 text-sm leading-relaxed text-foreground"><strong>Your honesty is key.</strong> We&rsquo;ll verify every review, and you&rsquo;ll have the option to publish yours anonymously.</p>}
    <div data-step="1" hidden={step !== 1} className="mt-6 space-y-5"><Field name="vendorName" text="Vendor(s) / company name" required /><Select name="category" text="Category" options={categories} required /><Area name="scope" text="What did you hire them to do?" required /><Field name="workPeriod" text="When did you work together?" placeholder="e.g. 2025–2026" required /><div className="grid gap-5 sm:grid-cols-2"><Field name="vendorContactName" text="Who did you work with? (optional)" /><Field name="vendorContactEmail" text="Their email address (optional)" type="email" /></div></div>
    <div data-step="2" hidden={step !== 2} className="mt-6 grid gap-5 sm:grid-cols-2">{[["quality", "Quality of work"], ["communication", "Communication"], ["delivery", "On-time delivery"], ["value", "Value for cost"], ["expectations", "Promise vs. delivery"], ["stageFit", "Fit for your stage"]].map(([n, t]) => <Rating key={n} name={n} text={t} />)}<div className="sm:col-span-2"><Select name="disappointed" text="Imagine you needed similar work again. If this vendor were unavailable, how would you feel?" options={["Very disappointed", "Somewhat disappointed", "Not disappointed", "Relieved"]} required /></div></div>
    <div data-step="3" hidden={step !== 3} className="mt-6 space-y-5"><Select name="companyStage" text="Your company stage at the time" options={["Pre-revenue", "Under $1M revenue", "$1M–$5M revenue", "$5M–$20M revenue", "$20M+ revenue", "Prefer not to say"]} required /><Select name="investment" text="Approximate cost" options={["Under $5K", "$5K–$15K", "$15K–$50K", "$50K–$100K", "$100K+", "Monthly retainer", "Prefer not to say"]} /><Area name="bestFor" text="Who are they a great fit for? (optional)" /></div>
    <div data-step="4" hidden={step !== 4} className="mt-6 space-y-5"><Area name="knowBeforeHiring" text="What should another founder know? (optional)" placeholder="Strengths, tradeoffs, pricing context, or contractual gotchas." /><div className="grid gap-5 sm:grid-cols-2"><Field name="firstName" text="First name" defaultValue={profile?.firstName} required /><Field name="lastName" text="Last name" defaultValue={profile?.lastName} required /><Field name="email" text="Work email" type="email" defaultValue={profile?.email} required /><Field name="brand" text="Company / brand" defaultValue={profile?.brand} required /></div><Select name="attribution" text="Review attribution" options={["Show my name and company", "Show “Verified CPG Founder”"]} defaultValue={profile?.attribution} required /><label className="flex items-start gap-3 text-sm text-muted"><input type="checkbox" name="certification" value="confirmed" required className="mt-1 h-4 w-4 accent-[var(--accent)]" />This reflects my genuine first-hand experience.</label></div>
    <div className="mt-8 flex gap-3">{step > 1 && <button type="button" onClick={() => setStep(x => x - 1)} className="rounded-lg border border-border px-5 py-3 font-bold hover:bg-background">Back</button>}<button type="submit" disabled={status === "loading"} className="flex-1 rounded-lg bg-accent px-5 py-3 font-bold text-white hover:bg-accent-dark">{status === "loading" ? "Submitting…" : step === 4 ? "Submit recommendation" : "Continue"}</button></div>{error && <p className="mt-3 text-center text-sm text-red-600">{error}</p>}<p className="mt-4 text-center text-xs text-muted">Your information is used only to verify and operate CPG Match.</p>
  </form>;
}

function Field({ name, text, type = "text", required, placeholder, defaultValue }: { name: string; text: string; type?: string; required?: boolean; placeholder?: string; defaultValue?: string }) { return <div><label className={label} htmlFor={name}>{text}{required && " *"}</label><input className={input} id={name} name={name} type={type} required={required} placeholder={placeholder} defaultValue={defaultValue} /></div>; }
function Area({ name, text, required, placeholder }: { name: string; text: string; required?: boolean; placeholder?: string }) { return <div><label className={label} htmlFor={name}>{text}{required && " *"}</label><textarea className={input} id={name} name={name} required={required} placeholder={placeholder} rows={3} /></div>; }
function Select({ name, text, options, required, defaultValue }: { name: string; text: string; options: string[]; required?: boolean; defaultValue?: string }) { return <div><label className={label} htmlFor={name}>{text}{required && " *"}</label><select className={input} id={name} name={name} required={required} defaultValue={defaultValue || ""}><option value="" disabled>Select one</option>{options.map(x => <option key={x}>{x}</option>)}</select></div>; }
function Rating({ name, text }: { name: string; text: string }) { return <Select name={name} text={text} required options={["5 — Excellent", "4 — Very good", "3 — Okay", "2 — Disappointing", "1 — Poor"]} />; }
function Submit({ status, text, error }: { status: Status; text: string; error: string }) { return <div className="mt-7"><button disabled={status === "loading"} className="w-full rounded-lg bg-accent px-6 py-3.5 font-bold text-white hover:bg-accent-dark">{status === "loading" ? "Submitting…" : text}</button>{error && <p className="mt-3 text-center text-sm text-red-600">{error}</p>}<p className="mt-3 text-center text-xs text-muted">We never sell founder data.</p></div>; }
function Success({ title, copy }: { title: string; copy: string }) { return <div className="py-10 text-center"><span className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-accent-light text-2xl text-accent">✓</span><h3 className="mt-5 text-2xl font-bold">{title}</h3><p className="mt-3 text-muted">{copy}</p></div>; }
