import { getSupabaseAdmin } from "@/lib/supabase";
import { LogoutButton } from "./logout-button";

export const dynamic = "force-dynamic";
type Entry = { id: string; submission_type: string; first_name: string; last_name: string; email: string; brand: string; vendor_name: string | null; vendor_category: string | null; payload: Record<string, unknown>; created_at: string };

export default async function CpgMatchAdminPage() {
  const supabase = getSupabaseAdmin();
  const { data, error } = supabase ? await supabase.from("cpg_match_submissions").select("*").order("created_at", { ascending: false }) : { data: [], error: new Error("Supabase is not configured") };
  const entries = (data || []) as Entry[]; const reviews = entries.filter(x => x.submission_type === "recommendation"); const waitlist = entries.filter(x => x.submission_type === "waitlist");
  return <div className="cpg-match-page min-h-screen bg-background"><header className="border-b border-border bg-white"><div className="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:px-6"><div><strong className="text-lg">CPG Match</strong><span className="ml-2 text-sm text-muted">Admin</span></div><div className="flex items-center gap-5"><a href="https://cpgmatch.com" className="text-sm font-semibold text-accent">View site ↗</a><LogoutButton /></div></div></header><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="flex flex-wrap items-end justify-between gap-5"><div><h1 className="text-3xl font-bold">Submissions</h1><p className="mt-1 text-muted">Founder reviews and database waitlist signups.</p></div><a href="/api/cpg-match-admin/export" className="rounded-lg border border-border bg-white px-4 py-2 text-sm font-bold hover:border-accent">Export CSV</a></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><Stat label="Total" value={entries.length} /><Stat label="Vendor reviews" value={reviews.length} /><Stat label="Waitlist" value={waitlist.length} /></div>{error && <p className="mt-6 rounded-lg bg-red-50 p-4 text-red-700">Could not load submissions: {error.message}</p>}<div className="mt-7 space-y-3">{entries.map(entry => <details key={entry.id} className="group rounded-xl border border-border bg-white"><summary className="grid cursor-pointer list-none gap-2 p-5 sm:grid-cols-[110px_1fr_1fr_150px] sm:items-center"><span className={`w-fit rounded-full px-2.5 py-1 text-xs font-bold ${entry.submission_type === "recommendation" ? "bg-accent-light text-accent" : "bg-blue-50 text-ridge"}`}>{entry.submission_type === "recommendation" ? "Review" : "Waitlist"}</span><span><strong>{entry.vendor_name || `${entry.first_name} ${entry.last_name}`}</strong><small className="block text-muted">{entry.vendor_category || entry.brand}</small></span><span className="text-sm"><a href={`mailto:${entry.email}`} className="text-accent">{entry.email}</a><small className="block text-muted">{entry.brand}</small></span><time className="text-sm text-muted">{new Date(entry.created_at).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</time></summary><div className="border-t border-border p-5"><dl className="grid gap-x-8 gap-y-4 sm:grid-cols-2">{Object.entries(entry.payload || {}).filter(([key, value]) => key !== "type" && value !== "" && value != null).map(([key, value]) => <div key={key}><dt className="text-xs font-bold uppercase tracking-wide text-muted">{key.replace(/([A-Z])/g, " $1")}</dt><dd className="mt-1 whitespace-pre-wrap text-sm">{Array.isArray(value) ? value.join(", ") : String(value)}</dd></div>)}</dl></div></details>)}{!entries.length && !error && <p className="rounded-xl border border-border bg-white p-10 text-center text-muted">No submissions yet.</p>}</div></main></div>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-xl border border-border bg-white p-5"><div className="text-3xl font-bold">{value}</div><div className="mt-1 text-sm text-muted">{label}</div></div>; }
